<?php
function page_top(string $title): void { $u=user(); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($title) ?> | EPMS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link href="assets/style.css" rel="stylesheet"></head><body>
<nav class="navbar navbar-expand-lg navbar-dark app-nav"><div class="container"><a class="navbar-brand fw-bold" href="index.php"><i class="bi bi-cash-stack me-2"></i>EPMS</a><button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="nav"><ul class="navbar-nav ms-auto align-items-lg-center gap-lg-1">
<?php if (is_admin()): ?><li class="nav-item"><a class="nav-link" href="index.php?page=dashboard">Dashboard</a></li><li class="nav-item"><a class="nav-link" href="index.php?page=employees">Employees</a></li><li class="nav-item"><a class="nav-link" href="index.php?page=masters">Masters</a></li><li class="nav-item"><a class="nav-link" href="index.php?page=attendance">Attendance</a></li><li class="nav-item"><a class="nav-link" href="index.php?page=leaves">Leaves</a></li><li class="nav-item"><a class="nav-link" href="index.php?page=payslips">Payslips</a></li><li class="nav-item"><a class="nav-link" href="index.php?page=reports">Reports</a></li><?php else: ?><li class="nav-item"><a class="nav-link" href="index.php?page=employee_dashboard">Dashboard</a></li><li class="nav-item"><a class="nav-link" href="index.php?page=profile">Profile</a></li><li class="nav-item"><a class="nav-link" href="index.php?page=my_attendance">Attendance</a></li><li class="nav-item"><a class="nav-link" href="index.php?page=my_leaves">Leaves</a></li><li class="nav-item"><a class="nav-link" href="index.php?page=my_payslips">Payslips</a></li><?php endif; ?><li class="nav-item dropdown ms-lg-2"><a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"><i class="bi bi-person-circle me-1"></i><?= e(($u['first_name'] ?? '') . ' ' . ($u['last_name'] ?? '')) ?></a><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="index.php?action=logout">Sign out</a></li></ul></li></ul></div></div></nav><main class="container py-4 py-lg-5"><?php show_flash(); ?>
<?php }
function page_bottom(): void { ?></main><footer class="text-center text-secondary pb-4 small">Employee Payroll Management System &middot; DBMS Project</footer><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script></body></html><?php }
function section_title(string $title, string $subtitle='', string $action=''): void { echo '<div class="d-flex align-items-start justify-content-between gap-3 mb-4"><div><h1 class="h2 fw-bold mb-1">'.e($title).'</h1><p class="text-secondary mb-0">'.e($subtitle).'</p></div>'.$action.'</div>'; }
?>
